### ISSUE TITLE
Builds Failing with 4.2.5 from My Fork

### ISSUE THREAD

**Issue by GitPuffy** [Wonderfall/docker-mastodon#11]
Hello, I forked your project quite some time ago and have been able to update the Dockerfile as Mastodon releases new versions and have my own "project build" based on my slight changes.

Since the 4.2.5 release of Mastodon all of my builds are failing.  I even went back and tried to build a 4.2.4 version and it failed also.  I do not see anything glaring in your Dockerfile or build.yml that differs from mine.  Did you have to build your 4.2.5 in some sort of special way?  If you kicked off a manual build would it finish successfully?

I am curious.  Thank you.

**Comment by Wonderfall** [comment]
There was an issue on new installs that got fixed with 4.2.7, maybe try again now.

**Comment by GitPuffy** [comment]
Yes I see my build from earlier today on 4.2.7 did finish successfully.  It was strange that your build of 4.2.5 worked but mine a day or so later did not.  4.2.6 did not build either.   I am going to close this issue as it really isn't an issue of yours.
