### ISSUE TITLE
Suggestion: all in one misskey docker

### ISSUE THREAD

**Issue by zhengfan2014** [Wonderfall/docker-mastodon#6]
I discovered misskey, which is a social network similar to mastodon. I hope there is an all in one docker.thank !
Maybe what I said is strange, sorry I don’t speak English very well, I use Google Translate

[misskey](https://github.com/syuilo/misskey)

**Comment by Wonderfall** [comment]
Sounds neat, but I can't maintain something that I don't use. Hopefully this image can inspire you to make your all-in-one misskey Docker image (although it seems already [pretty simple](https://github.com/misskey-dev/misskey/blob/develop/docker-compose.yml) to install).

Have a nice day!
